FROM python:3.7-slim

ENV TZ=Asia/Bangkok
RUN mkdir /app
COPY . /app

RUN pip install -r /app/requirements.txt

WORKDIR /app/send
RUN mkdir -p ./database
RUN mkdir -p ./media

RUN python manage.py migrate --noinput

RUN useradd -u 1000 -d /app -M -s /bin/sh user && \
    chown -R user:user database && \
    chown -R user:user media && \
    chmod 755 /app

USER user

CMD ["python", "-u", "/app/send/job_delete_expire_file.py"]
