# Generated by Django 2.1 on 2020-08-21 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import upload.helper_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('downloaded_by', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'download_log',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('max_downloads', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to=upload.helper_functions.modify_name)),
                ('ref_key_download', models.CharField(max_length=32)),
                ('ref_key_delete', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['ref_key_download'], name='upload_ref_key_72891a_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['ref_key_delete'], name='upload_ref_key_0b398c_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['expire_date', 'is_active'], name='upload_expire__bf330a_idx'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
    ]
